apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fatihsevban/ecommerce-frontend
---
apiVersion: v1
kind: Service
metadata:
  name:  frontend-srv
spec:
  selector:
    app: frontend
  type:  ClusterIP
  ports:
    - name:  frontend
      port:  8080
      targetPort:  8080